name: Lint
on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Setup Rome
        uses: rome/setup-rome@v0.5
        with:
          version: latest 

      - name: Import Rome config file
        run: wget -O rome.json https://raw.githubusercontent.com/michijs/.github/main/rome.json

      - name: Run Rome format
        run: rome format --write --json .

      - name: Check for changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Skipping next format steps."
          else
            echo "Changes detected. Proceeding with next steps."
            echo "FORMAT_CHANGES_DETECTED=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.FORMAT_CHANGES_DETECTED == 'true'
        run: |
          git add .
          git commit -m "Format changes"

      - name: Push changes
        if: env.FORMAT_CHANGES_DETECTED == 'true'
        run: git push origin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Rome check
        run: rome check --apply . || true

      - name: Check for changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes detected. Skipping next steps."
          else
            echo "Changes detected. Proceeding with next steps."
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          fi

      - name: Remove refs/heads prefix from github.ref (if exists)
        run: |
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            BRANCH_NAME=$(echo "${{ github.ref }}" | cut -c 12-)
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV
          fi

      - name: Delete existing branch (if exists)
        run: |
          git push origin --delete ${{ env.BRANCH_NAME }}_lint || true

      - name: Create new branch
        if: env.CHANGES_DETECTED == 'true'
        run: git checkout -b ${{ env.BRANCH_NAME }}_lint

      - name: Commit changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add .
          git commit -m "Linting changes"

      - name: Push changes
        if: env.CHANGES_DETECTED == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}_lint

      - name: Create pull request
        if: env.CHANGES_DETECTED == 'true'
        run: |
            SUGGESTIONS=$(rome check --json . 2>&1 || true)
            gh pr create -B ${{ env.BRANCH_NAME }} -H ${{ env.BRANCH_NAME }}_lint --title 'Linting changes' --body "This pull request includes linting changes based on the target branch.

            Please review and merge if everything looks good.
            
            <details>
              <summary>Additional suggestions:</summary>
              ${SUGGESTIONS}
            </details>
            "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
